version: '3.8'

networks:
  dbt_examples:
    name: dbt_examples
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - dbt_examples
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: main
    volumes:
      - ./postgres/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/app:/app
      - ./postgres/output:/output
    ports:
      - "5432:5432"
