data_quality:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: myuser
      pass: mypassword
      dbname: main
      schema: public

  target: dev

incremental_models:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: myuser
      pass: mypassword
      dbname: main
      schema: public

  target: dev
