version: 2

sources:
  - name: data_quality
    database: main
    schema: public
    tables:
      - name: users
        columns:
          - name: username
            tests:
              - not_null
          - name: email
            tests:
              - not_null
              - unique
              - not_empty

models:
  - name: users_checks
    columns:
      - name: username
        description: "The username of the user"
        tests:
          - not_null
      - name: email
        description: "The email of the user"
        tests:
          - not_null
          - unique
